#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the reverseArray function below.
from numpy import append


def reverseArray(a):
    b = []
    for i in reversed(range(len(a))):
        b.append(a[i])
    for j in b:
        print(j,end= " ")




if __name__ == '__main__':
    arr_count = int(input())

    lst = [int(x) for x in input().split()]


    res = reverseArray(lst)
